project/aici/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import AiciLoginView

app_name="aici"

urlpatterns = [
    path('', AiciLoginView.as_view(template_name='aici/login.html'), name='login'), #로그인페이지
    path('logout/', views.logout_view, name='logout'), 
    path('main/', views.main, name='main'), #메인페이지
    path('main/voc/', views.voc, name='voc'), #voc현황페이지
    path('main/work/', views.work, name='work'), #사외공사
    path('edit_voc/', views.edit_voc, name='edit_voc'), #사외공사
    path('send_mms_proxy/', views.send_mms_proxy, name='send_mms_proxy'),
    path('export1/', views.gongsa_excel, name='gongsa_excel'),
    path('export2/', views.voc_excel, name='voc_excel'),
    # path('update-voc-status/', views.update_voc_status, name='update_voc_status'),

    path('chatbot/', views.chat, name='chatbot'),    
    path('chatbot/<str:phone>/', views.chatbot, name='chat'),
    path('positive/', views.positive, name='positive'),
    path('negative/', views.negative, name='negative'), #메인페이지


]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('aici/', include('aici.urls')),
    path('gongsa/', include('Gongsa.urls')),
]

project/aici/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from django.contrib.auth.models import User

class VOC(models.Model):
    REPAIR_STATUS_CHOICES = [
        ('수리중', '수리중'),
        ('수리완료', '수리완료'),
        ('수리전', '수리전'),
    ]

    VOC_STATUS_CHOICES = [
        ('확인중', '확인중'),
        ('확인완료', '확인완료'),
        ('추가조치필요', '추가조치필요'),
        ('발송전', '발송전'),
    ]


    phone = models.CharField(max_length=20) 
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    tt = models.CharField(max_length=30) 
    updated_at = models.DateField(auto_now=True)
    repair_status = models.CharField(max_length=100, choices=REPAIR_STATUS_CHOICES)
    voc_status = models.CharField(max_length=100, choices=VOC_STATUS_CHOICES, null=True)
    comment = models.TextField(max_length=100, blank=True, null=True) #사용자의견
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.phone
    

    @classmethod
    def get_preparing_vocs(cls):
        return cls.objects.filter(voc_status='발송전').count()

    @classmethod
    def get_processing_vocs(cls):
        return cls.objects.filter(voc_status='확인중').count()

    @classmethod
    def get_reprocessing_vocs(cls):
        return cls.objects.filter(voc_status='추가조치필요').count()

    @classmethod
    def get_completed_vocs(cls):
        return cls.objects.filter(voc_status='확인완료').count()

project/aici/views.py
from io import BytesIO
import time
from django.shortcuts import render
from django.http import HttpResponse
from Gongsa.models import Post
from aici.models import VOC
from datetime import datetime
from datetime import date, timedelta
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.http import HttpResponseNotAllowed
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
import requests
import json
from django.http import JsonResponse
import base64
import hashlib
import hmac
import pandas as pd
from openpyxl import Workbook
import pickle

import pandas as pd
import numpy as np
import os
from django.conf import settings
from konlpy.tag import Mecab
#123
def classify_emotion(text):
    with open('/mnt/c/Users/User/Desktop/AICI1/AI_8_31/wv_model.pt', 'rb') as fr:
        wv_model = pickle.load(fr)
    with open('/mnt/c/Users/User/Desktop/AICI1/AI_8_31/ML_model.pt', 'rb') as fr:
        ml_model = pickle.load(fr)

    mecab = Mecab()
    
    my_word=mecab.morphs(text)
    feature_vec = np.zeros((200), dtype="float32")
    n_words = 0
    for word in my_word:
        if word in wv_model.wv.key_to_index:
            n_words += 1
            # 임베딩 벡터에 해당 단어의 벡터를 더함
            feature_vec = np.add(feature_vec, wv_model.wv[word])
    # 단어 개수가 0보다 큰 경우 벡터를 단어 개수로 나눠줌 (평균 임베딩 벡터 계산)
    if (n_words > 0):
        feature_vec = np.divide(feature_vec, n_words)
    tmp=[]
    tmp.append(feature_vec)
    # 입력된 내용을 감정 분류 모델로 분석하여 결과를 반환
    result = ml_model.predict(tmp)
    return 'positive' if result == 0 else 'negative'

def chatbot(request, phone):
    if request.method == 'POST':
        comment = request.POST.get('comment')
        voc = VOC.objects.get(phone=phone)
        voc.comment = comment

        # 감정 분류 모델을 사용하여 입력된 내용을 분석하여 결과에 따라 voc_status 변경
        emotion = classify_emotion(comment)
        if emotion == 'positive':
            voc.voc_status = '최종완료'
            voc.delete()  # 데이터 삭제
            voc.save()  # 변경사항 저장   
        else:
            voc.voc_status = '추가조치필요'

        voc.save()  # 변경사항 저장

        if emotion == 'positive':
            return redirect('aici:positive')
        else:
            return redirect('aici:negative')
    else:
        voc = VOC.objects.get(phone=phone)
        return render(request, 'aici/chatbot.html', {'voc': voc})
    

def chat(request):
    if request.method == 'POST':
        response_text = request.POST['comment']
        if response_text == '네':
            return redirect('aici:positive')
        elif response_text == '아니오':
            return redirect('aici:negative')
    return render(request, 'aici/chat.html')

# @login_required
# def chatbot(request, phone):
#     if request.method == 'POST':
#         comment = request.POST.get('comment')
#         voc = VOC.objects.get(phone=phone)
#         voc.comment = comment

#         if comment.lower() == '네':
#             voc.voc_status = '확인완료'
#             voc.delete()  # 데이터 삭제
#             voc.save()  # 변경사항 저장            
#             return redirect('aici:positive')
#         elif comment.lower() == '아니오':
#             voc.voc_status = '추가조치필요'
#             voc.save()  # 변경사항 저장
#             return redirect('aici:negative')
#         else:
#             voc.save()  # 변경사항 저장

#             return redirect('aici:chat', phone=phone)
#     else:
#         voc = VOC.objects.get(phone=phone)
#         return render(request, 'aici/chatbot.html', {'voc': voc})


def positive(request):
    # positive 뷰의 내용을 작성하세요
    return render(request, 'aici/positive.html')

def negative(request):
    # negative 뷰의 내용을 작성하세요
    return render(request, 'aici/negative.html')

class AiciLoginView(LoginView):
    template_name = 'aici/login.html'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, username=username, password=password)

        if user is not None:
            if user.groups.filter(name='aici').exists():
                # gongsa 그룹에 있는 사용자인 경우 로그인 처리
                login(self.request, user)
                return redirect('aici:main')  # 로그인 후 리디렉션할 페이지
            elif user.groups.filter(name='gongsa').exists():
                # aici 그룹에 있는 사용자인 경우 로그인 거부
                error_message = 'Please enter a correct username and password. Note that both fields may be case-sensitive.'
                return render(self.request, 'aici/login.html', {'error_message': error_message})
        else:
            # 인증 실패
            error_message = 'Invalid credentials.'
            return render(self.request, 'aici/login.html', {'error_message': error_message})

def logout_view(request):
    logout(request)
    return redirect('aici:login')

@login_required
def main(request):
    
    xData_gongsa, yData_gongsa = gongsa_graph(request)
    xData_voc, yData_voc = voc_graph(request)

    registered_constructions = Post.get_registered_constructions()
    daily_constructions = Post.get_daily_constructions()
    weekly_constructions = Post.get_weekly_constructions()

    preparing_vocs = VOC.get_preparing_vocs()
    processing_vocs = VOC.get_processing_vocs()
    reprocessing_vocs = VOC.get_reprocessing_vocs()
    completed_voc = VOC.get_completed_vocs()


    context = {
        'registered_constructions': registered_constructions,
        'daily_constructions': daily_constructions,
        'weekly_constructions': weekly_constructions,
        'preparing_vocs': preparing_vocs,
        'processing_vocs': processing_vocs,
        'reprocessing_vocs': reprocessing_vocs,
        'completed_voc': completed_voc,
        'xData_gongsa': xData_gongsa,
        'yData_gongsa': yData_gongsa,
        'xData_voc': xData_voc,
        'yData_voc': yData_voc,
    }
    return render(request, 'aici/main.html', context)



@login_required
def voc(request):
    voc_data = VOC.objects.filter(author=request.user).order_by('-created_at', '-id')
    context = {
        'voc_data': voc_data
    }
    return render(request, 'aici/voc.html', context)

from django.db.models import Q

@login_required
def work(request):
    if request.method == 'GET':
        start_date = request.GET.get('start_at')
        end_date = request.GET.get('end_at')
        posts = Post.objects.all()
        error_message = ""

        if start_date and end_date:
            start_date = datetime.strptime(start_date, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
            posts = posts.filter(Q(start_at__range=[start_date, end_date]) | Q(end_at__range=[start_date, end_date]))
        elif start_date:
            error_message = "종료일을 선택해주세요."
        elif end_date:
            error_message = "시작일을 선택해주세요."

        context = {'posts': posts, 'start_date': start_date, 'end_date': end_date, 'error_message': error_message}
    else:
        context = {}

    return render(request, 'aici/work.html', context)

@login_required
def edit_voc(request):
    voc = VOC.objects.first()  # 가져올 VOC 인스턴스를 선택하는 방법에 따라 적절한 쿼리를 사용합니다.
    comment = voc.comment if voc else None

    context = {
        'comment': comment,
    }


    return render(request, 'aici/edit_voc.html', context)


@login_required
def gongsa_graph(request):
    today = date.today()
    end_date = today + timedelta(days=6)

    xData = [str(today + timedelta(days=i)) for i in range((end_date - today).days + 1)]

    yData = [Post.objects.filter(start_at=date_val).count() for date_val in xData]

    # Check if today's date is in xData
    if str(today) not in xData:
        xData.append(str(today))
        yData.append(0)

    return xData, yData

@login_required
def voc_graph(request):
    current_datetime = timezone.now()
    start_datetime = current_datetime.replace(minute=0, second=0, microsecond=0) - timezone.timedelta(hours=23)
    end_datetime = current_datetime.replace(minute=0, second=0, microsecond=0) + timezone.timedelta(hours=1)

    xData = []
    yData = []

    for i in range(24):
        hour_start = start_datetime + timezone.timedelta(hours=i)
        hour_end = start_datetime + timezone.timedelta(hours=i+1)

        count = VOC.objects.filter(
            voc_status__in=['발송전', '추가조치필요'],
            created_at__gte=hour_start,
            created_at__lt=hour_end
        ).count()
        xData.append(hour_start.strftime("%H"))
        yData.append(count)

    # # 현재 시간
    # xData.append(current_datetime.strftime("%Y-%m-%d %H:%M:%S"))
    # yData.append(VOC.objects.filter(voc_status__in=['발송전', '확인중', '추가조치필요'], created_at__range=(end_datetime, current_datetime)).count())

    return xData, yData



def send_mms_proxy(request):
    url = "https://sens.apigw.ntruss.com"
    uri = "/sms/v2/services/" + "ncp:sms:kr:310425331464:mms_chat" + "/messages"
    api_url = url + uri
    timestamp = str(int(time.time() * 1000))
    access_key = "43Q01oRn0O7n6hgLV0xi"
    string_to_sign = "POST " + uri + "\n" + timestamp + "\n" + access_key
    signature = make_signature(string_to_sign)
    
    voc_status = '확인중'
    data = json.loads(request.body)
    selected_phone_numbers = data.get('phone_numbers', [])
    for phone_number in selected_phone_numbers:
        headers = {
            'Content-Type': 'application/json; charset=utf-8',
            'x-ncp-apigw-timestamp': timestamp,
            'x-ncp-iam-access-key': access_key,
            'x-ncp-apigw-signature-v2': signature
        }

    
        body = {
            "type": "LMS",
            "countryCode": "82",
            "from": "01044339761",
            "subject": "MMS 제목",
            "contentType": "COMM",
            "content": "MMS 내용",
            "messages": [
                {

project/aici/templates/aici/chat.html
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static '/chatbot.css' %}">
    <link rel="stylesheet" href={% static 'index3_styles.css' %}/>
    <!-- Add any other static file connections (CSS files, etc.) here -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'chatbot.js' %}"></script>
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
    
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav"  style='background-color: #0AA2B9;'>
        <div class="container">
            <p float='left'><img src={% static 'images/kt_logo2.png' %} alt="My Image" width="45" height="45"></p>
            <div style='margin: 0 auto; font-size: 20px; color: #ffffff;' class='kt-ai-bot'>
            kt AI봇
            </div>
        </div>
    </nav>


    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Freelancer - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top" style='background-color: #ECEDF0'>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container">
                <div class="row justify-content-center" style="width: 100%; height: 75%;">
                    <div style="margin-left: 30px; width:100%; position: relative; vertical-align: middle;">
                        <img src="{% static 'images/말풍선.png' %}" alt="My Image" style='width: 100%; height: 80%;'>
                    <p class="typing-txt">안녕하십니까? 접수해주신 nw 장애 처리해드렸는데 수리 완료 되었을까요? 수리가 완료되지 않았거나 불편사항이 있으시다면 말씀해주세요.</p> 
                        <p class="typing"></p>
                    </div>
                    <div class = 'input_div' style=" width:100%" >
                        <img class ="standing" src="{% static 'images/꾸벅듀오.png' %}"  alt="hello_image" width="80%" height="auto">
                    </div>
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- * * SB Forms Contact Form * *-->
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- This form is pre-integrated with SB Forms.-->
                    <!-- To make this form functional, sign up at-->
                    <!-- https://startbootstrap.com/solution/contact-forms-->
                    <!-- to get an API token!-->
                    <div id="contactForm" data-sb-form-api-token="API_TOKEN" style="padding-bottom:0%;">
                        <!-- Sentence input-->
                        <div class="row input-group-newsletter input_div">
                            <div class="col">
                                <form method="post" action="{% url 'aici:chatbot' %}">
                                    {% csrf_token %}
                                    <div class="input-group">
                                        <input class="form-control" id="comment" type="sentence" placeholder="내용을 입력해주세요." onkeydown="handleKeyDown(event)" data-sb-validations="required,sentence" />
                                        <button class="btn btn-primary" id="send-button" type="submit" style='background-color: #0AA2B9'>전송</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        
                        <div class="invalid-feedback mt-2" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback mt-2" data-sb-feedback="email:email">Email is not valid.</div>
                        <!-- Submit success message-->
                        <!---->
                        <!-- This is what your users will see when the form-->
                        <!-- has successfully submitted-->
                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3 mt-2">
                                <div class="fw-bolder">Form submission successful!</div>
                                To activate this form, sign up at
                                <br />
                                <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                            </div>
                        </div>
                        <!-- Submit error message-->
                        <!---->
                        <!-- This is what your users will see when there is-->
                        <!-- an error submitting the form-->
                        <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3 mt-2">Error sending message!</div></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <style>
            .standing {margin-bottom: 50px;
               }
               html,
               body {
                 width: 100%;
                 height: 100%;
               }
               .masthead {
                 width: 100%;
                 height: 100%;
               }
        </style>
    </body>


    <script>
        var typingBool = false;
    var typingIdx = 0;

    var typingTxt = $(".typing-txt").text();

    typingTxt = typingTxt.split("");

    if (typingBool == false) {
    typingBool = true;
    var tyInt = setInterval(typing, 100);
    }

    function typing() {
    if (typingIdx < typingTxt.length) {
        $(".typing").append(typingTxt[typingIdx]);
        typingIdx++;
    } else {
        clearInterval(tyInt);
    }
    }
    document.addEventListener('DOMContentLoaded', function() {
        var sendButton = document.querySelector('.send-button');
        sendButton.addEventListener('click', checkResponse);
    });

    function handleKeyDown(event) {
        if (event.key === 'Enter') { // Enter 키를 눌렀을 때
            checkResponse();
        }
    }

    function checkResponse() {
        var response = document.querySelector('.chatting-textbox').value;
        if (response === '네') {
            window.location.href = "{% url 'aici:positive' %}";
        } else if (response === '아니요') {
            window.location.href = "{% url 'aici:negative' %}";
        }
    }

    </script>
</html>


{% endblock %}

project/aici/templates/aici/edit_voc.html
{% extends "aici/base.html" %}

{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static '/edit_voc.css' %}">
    <script src="{% static '/edit_voc.js' %}"></script>

    <!-- Add any other static file connections (CSS files, etc.) here -->
{% endblock %}

{% block content %}
<div class="modal">
  <div class="modal_body">
    <h2>사용자의견</h2>

    <div class="form-group">
      <label for="id_comment">Comment</label>
      
      <textarea class="form-control" id="id_comment" name="comment" rows="3" readonly>{{ comment }}</textarea>
      <button class="return-button" onclick='edit_cancel()'>돌아가기</button>
    </div>

  </div>
</div>
{% endblock %}

project/aici/templates/aici/form_errors.html
<!-- users>form_errors.html -->

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div>
  <strong>{{ field.label }}</strong>
  {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div>
  <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

project/aici/templates/aici/work.html
<!-- work.html -->

{% load static %}
{% block static %}
    <!-- Add static code (such as linking CSS files) here -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'work.css' %}">
    <link href="{% static 'index3_styles.css' %}" rel="stylesheet" />
    <script src="{% static 'work.js' %}"></script> <!-- Add this line to include the JavaScript file -->
    <script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
    <title>공사현황</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'images/kt.png' %}" />
    
    {% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
            <img src={% static 'images/Logo.png' %} alt="My Image" width="140" height="45">
    </div>
  </nav>
  
  <body id="page-top">


    <!-- Rest of your template code -->

    <header class="masthead text-center">
        <div class="container d-flex align-items-center ">
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0" style="font-family:Y너만을비춤체;">공사현황</h1>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0 p-2" style="font-family:Nanum Gothic;">/ 현재 공사현황을 확인하실 수 있습니다.</p>
        </div>
    </header>

        <section class="page-section portfolio" id="portfolio">
            
            <div class="container">
                <div class="container-fluid">
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <form id="search-form" >
                                <label class='label_date' style="font-family:Y너만을비춤체;">해당기간 내 진행중인 공사확인</label>
                                <label class='label_date' style="font-family: Y너만을비춤체;" for="start-date"></label>
                                <input class='select_date' type="date" id="start-date" name="start_at">
                                <label class='label_date' style="font-family: Y너만을비춤체;"> ~ </label>
                                <label class='label_date' style="font-family: Y너만을비춤체;" for="end-date"></label>
                                <input type="date" id="end-date" name="end_at">
                                <button class="search_button" id="search-button" type="submit">🔍</button> <!-- Add id="search-button" to the search button -->
                                <button class='to-excel-button2' onclick='exportAllToExcel()' type='button' style="font-family: Nanum Gothic;">엑셀로 보내기</button>
                            </form>
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="text-align:center; vertical-align: center;">
                                    <thead style="font-size:20px; font-weight:900;">
                                        <tr bgcolor="#F5F5F5">
                                            <th>#</th>
                                            <th>접수기관</th>
                                            <th>담당자</th>
                                            <th>연락처</th>
                                            <th>공사기간</th>
                                            <th>공사종류</th>
                                            <th>공사완료여부</th>
                                            <th>기타사항</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for post in posts %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ post.author.profile.agency }}</td>
                                            <td>{{ post.author }}</td>
                                            <td>{{ post.author.profile.phone }}</td>
                                            <td>{{ post.start_at }} ~ {{ post.end_at }}</td>
                                            <td>{{ post.construction_type }}</td>
                                            <td>{{ post.get_construction_status }}</td>
                                            <td > {{ post.content|slice:":5" }}
                                                {% if post.content|length > 5 %} 
                                                <button class="more-btn" data-bs-toggle="modal" data-bs-target='#more{{ forloop.counter }}'>...</button>
                                                {% endif %}
                                            </td>
                                        </tr>
                                        <!-- 모달 창 -->
                                        <div class="modal fade" id="more{{ forloop.counter }}" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h1 class="modal-title fs-5" style='font-family:Y너만을비춤체;' id="staticBackdropLabel">기타사항</h1>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label for="id_comment" style="font-family:Y너만을비춤체;">내용</label>
                                                            <textarea class="form-control" id="id_comment" name="comment" rows="3" readonly>{{ post.content }}</textarea>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">확인</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>

        </section>



    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>    
    <script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
    <script>
        function exportAllToExcel() {
            // 테이블 데이터 가져오기
            var table = document.querySelector('.table');
            var rows = table.getElementsByTagName('tr');
    
            // 테이블 헤더 가져오기
            var headerRow = rows[0];
            var headerData = [];
            var headerCells = headerRow.getElementsByTagName('th');
            for (var i = 0; i < headerCells.length; i++) {
                var headerCell = headerCells[i];
                headerData.push(headerCell.innerText);
            }
    
            // 테이블 데이터를 배열로 변환
            var data = [headerData];
            for (var i = 1; i < rows.length; i++) { // 첫 번째 행은 헤더이므로 제외
                var row = rows[i];
                var rowData = [];
                var cells = row.getElementsByTagName('td');
                for (var j = 0; j < cells.length; j++) {
                    var cell = cells[j];
                    rowData.push(cell.innerText);
                }
                data.push(rowData);
            }
    
            // 데이터를 Workbook으로 변환
            var workbook = XLSX.utils.book_new();
            var worksheet = XLSX.utils.aoa_to_sheet(data);
            XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1');
    
            // Workbook을 엑셀 파일로 저장
            var wbout = XLSX.write(workbook, { bookType: 'xlsx', type: 'binary' });
    
            function s2ab(s) {
                var buf = new ArrayBuffer(s.length);
                var view = new Uint8Array(buf);
                for (var i = 0; i < s.length; i++) {
                    view[i] = s.charCodeAt(i) & 0xFF;
                }
                return buf;
            }
    
            var blob = new Blob([s2ab(wbout)], { type: 'application/octet-stream' });
            var downloadLink = document.createElement('a');
            downloadLink.href = window.URL.createObjectURL(blob);
            downloadLink.download = 'gongsalist_data.xlsx';
            downloadLink.click();
        }
            // 에러 메시지가 있을 때 alert로 메시지를 띄웁니다.
        {% if error_message %}
        window.onload = function() {
            alert("{{ error_message }}");
        }
        {% endif %}
    </script>
{% endblock %}